{{- if .Values.rabbitmq.enabled }}
{{- $ns := include "bgc.namespace" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{ $ns }}
  labels:
    app: rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      {{- with .Values.rabbitmq.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          {{- with .Values.rabbitmq.imagePullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          {{- if or .Values.rabbitmq.includeSecret .Values.rabbitmq.includeConfig }}
          envFrom:
            {{- if .Values.rabbitmq.includeSecret }}
            - secretRef:
                name: {{ .Values.secretName }}
            {{- end }}
            {{- if and .Values.config.enabled .Values.rabbitmq.includeConfig }}
            - configMapRef:
                name: {{ .Values.config.name }}
            {{- end }}
          {{- end }}
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          {{- with .Values.rabbitmq.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.rabbitmq.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ $ns }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
{{- end }}
