{{- if .Values.redis.enabled }}
{{- $ns := include "bgc.namespace" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ $ns }}
  labels:
    app: redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          {{- with .Values.redis.imagePullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          ports:
            - containerPort: 6379
          {{- with .Values.redis.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.redis.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ $ns }}
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
{{- end }}
