{{- if .Values.worker.enabled }}
{{- $ns := include "bgc.namespace" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgc-data-portal-worker
  namespace: {{ $ns }}
  labels:
    app: bgc-data-portal-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: bgc-data-portal-worker
  template:
    metadata:
      labels:
        app: bgc-data-portal-worker
    spec:
      {{- with .Values.worker.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          {{- with .Values.worker.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.worker.image }}
          {{- with .Values.worker.imagePullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          {{- with .Values.worker.workingDir }}
          workingDir: {{ . }}
          {{- end }}
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          {{- with .Values.worker.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            {{- if .Values.worker.includeSecret }}
            - secretRef:
                name: {{ .Values.secretName }}
            {{- end }}
            {{- if and .Values.config.enabled .Values.worker.includeConfig }}
            - configMapRef:
                name: {{ .Values.config.name }}
            {{- end }}
          {{- with .Values.worker.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
