# Generated by Django 5.0.4 on 2025-05-16 09:42

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mgnify_bgcs", "0000_pgvector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bgc",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(max_length=255)),
                ("start_position", models.IntegerField()),
                ("end_position", models.IntegerField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("is_partial", models.BooleanField(default=False)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1152)),
            ],
        ),
        migrations.CreateModel(
            name="BgcClass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BgcDetector",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("tool", models.CharField(blank=True, max_length=255, null=True)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Biome",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lineage", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CurrentStats",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("acc", models.CharField(db_index=True, max_length=50, unique=True)),
                ("ref_db", models.CharField(db_index=True, max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneCaller",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("tool", models.CharField(blank=True, max_length=255, null=True)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_coord", models.FloatField()),
                ("y_coord", models.FloatField()),
                ("name", models.CharField(max_length=60)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=2)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("accession", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BgcBgcClass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bgc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mgnify_bgcs.bgc",
                    ),
                ),
                (
                    "bgc_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mgnify_bgcs.bgcclass",
                    ),
                ),
            ],
            options={
                "db_table": "app_bgcbgcclass",
            },
        ),
        migrations.AddField(
            model_name="bgc",
            name="classes",
            field=models.ManyToManyField(
                related_name="bgcs",
                through="mgnify_bgcs.BgcBgcClass",
                to="mgnify_bgcs.bgcclass",
            ),
        ),
        migrations.AddField(
            model_name="bgc",
            name="detector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bgcs",
                to="mgnify_bgcs.bgcdetector",
            ),
        ),
        migrations.CreateModel(
            name="Assembly",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("accession", models.CharField(max_length=255, unique=True)),
                ("collection", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "biome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assemblies",
                        to="mgnify_bgcs.biome",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assemblies",
                        to="mgnify_bgcs.study",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sequence_sha256",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("mgyc", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("source_organism", models.JSONField(blank=True, default=dict)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("sequence", models.TextField()),
                (
                    "assembly",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contigs",
                        to="mgnify_bgcs.assembly",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bgc",
            name="contig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bgcs",
                to="mgnify_bgcs.contig",
            ),
        ),
        migrations.CreateModel(
            name="Protein",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sequence", models.TextField()),
                (
                    "sequence_sha256",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1152)),
                (
                    "cluster_representative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cluster_members",
                        to="mgnify_bgcs.protein",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cds",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_position", models.IntegerField()),
                ("end_position", models.IntegerField()),
                ("strand", models.SmallIntegerField()),
                (
                    "protein_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pipeline_version", models.CharField(max_length=50)),
                (
                    "contig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cds",
                        to="mgnify_bgcs.contig",
                    ),
                ),
                (
                    "gene_caller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cds",
                        to="mgnify_bgcs.genecaller",
                    ),
                ),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cds",
                        to="mgnify_bgcs.protein",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProteinDomain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_position", models.IntegerField()),
                ("end_position", models.IntegerField()),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mgnify_bgcs.domain",
                    ),
                ),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mgnify_bgcs.protein",
                    ),
                ),
            ],
            options={
                "db_table": "app_proteindomain",
            },
        ),
        migrations.AddField(
            model_name="protein",
            name="domains",
            field=models.ManyToManyField(
                related_name="proteins",
                through="mgnify_bgcs.ProteinDomain",
                to="mgnify_bgcs.domain",
            ),
        ),
        migrations.AddIndex(
            model_name="bgcbgcclass",
            index=models.Index(
                fields=["bgc_class", "bgc"], name="idx_bgcbgc_class_bgc"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bgcbgcclass",
            unique_together={("bgc", "bgc_class")},
        ),
        migrations.AddIndex(
            model_name="bgc",
            index=models.Index(fields=["identifier"], name="idx_bgc_identifier"),
        ),
        migrations.AddIndex(
            model_name="bgc",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=512,
                fields=["embedding"],
                m=16,
                name="bgc_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="cds",
            index=models.Index(fields=["protein"], name="idx_cds_protein"),
        ),
        migrations.AddIndex(
            model_name="cds",
            index=models.Index(fields=["contig"], name="idx_cds_contig"),
        ),
        migrations.AddIndex(
            model_name="cds",
            index=models.Index(
                fields=["start_position", "end_position"], name="idx_cds_positions"
            ),
        ),
        migrations.AddIndex(
            model_name="proteindomain",
            index=models.Index(
                fields=["domain", "protein"], name="idx_protdomain_domain_prot"
            ),
        ),
        migrations.AddIndex(
            model_name="proteindomain",
            index=models.Index(
                fields=["protein", "domain"], name="idx_protdomain_prot_domain"
            ),
        ),
        migrations.AddIndex(
            model_name="proteindomain",
            index=models.Index(
                fields=["domain", "start_position", "end_position"],
                name="idx_protdomain_domain_position",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="proteindomain",
            unique_together={("protein", "domain", "start_position", "end_position")},
        ),
        migrations.AddIndex(
            model_name="protein",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=512,
                fields=["embedding"],
                m=16,
                name="protein_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
