# Generated by Django 5.0.4 on 2025-05-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
