# Generated by Django 5.0.4 on 2025-05-19 10:44

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0002_alter_domain_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bgc",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=200),
        ),
        migrations.AlterField(
            model_name="protein",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=200),
        ),
    ]
