# Generated by Django 5.0.4 on 2025-05-19 14:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0003_alter_bgc_embedding_alter_protein_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bgc",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1152),
        ),
        migrations.AlterField(
            model_name="protein",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1152),
        ),
    ]
