# Generated by Django 5.0.4 on 2025-05-23 11:38

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0004_alter_bgc_embedding_alter_protein_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bgc",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1152, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bgc",
            name="identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1152, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="bgc",
            constraint=models.UniqueConstraint(
                fields=("contig", "start_position", "end_position", "detector"),
                name="unique_bgc_region_per_contig_detector",
            ),
        ),
    ]
