# Generated by Django 5.0.4 on 2025-05-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0005_alter_bgc_embedding_alter_bgc_identifier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UMAPTransform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("n_samples_fit", models.PositiveIntegerField()),
                ("pca_components", models.PositiveIntegerField()),
                ("n_neighbors", models.PositiveSmallIntegerField()),
                ("min_dist", models.FloatField()),
                ("metric", models.CharField(max_length=50)),
                ("sklearn_version", models.CharField(max_length=50)),
                ("umap_version", models.CharField(max_length=50)),
                ("model_file", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
