# Generated by Django 5.0.4 on 2025-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0007_remove_umaptransform_model_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bgc",
            name="is_aggragated_region",
            field=models.BooleanField(default=False),
        ),
    ]
