# Generated by Django 5.0.4 on 2025-06-01 02:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0008_bgc_is_aggragated_region"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bgc",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="idx_bgc_metadata_gin"
            ),
        ),
    ]
