# Generated by Django 5.0.4 on 2025-06-02 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0009_bgc_idx_bgc_metadata_gin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bgc",
            old_name="is_aggragated_region",
            new_name="is_aggregated_region",
        ),
    ]
