# Generated by Django 5.0.4 on 2025-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0010_rename_is_aggragated_region_bgc_is_aggregated_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="contig",
            name="accession",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
