# Generated by Django 5.0.4 on 2025-06-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0011_contig_accession"),
    ]

    operations = [
        migrations.AddField(
            model_name="bgc",
            name="compounds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="contains dictionaries with compound representations. SMILEs are used as keys, and values are dictionaries with 'name' and 'type' keys.",
            ),
        ),
    ]
