# Generated by Django 5.0.4 on 2025-06-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0012_bgc_compounds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bgc",
            name="compounds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="contains dictionaries with compound representations. SMILEs are used as keys, and values are dictionaries with 'name' and 'type' keys.",
                null=True,
            ),
        ),
    ]
