# Generated by Django 5.0.4 on 2025-06-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0013_alter_bgc_compounds"),
    ]

    operations = [
        migrations.AddField(
            model_name="bgc",
            name="smiles_svg",
            field=models.CharField(blank=True, null=True),
        ),
    ]
