# Generated by Django 5.0.4 on 2025-06-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0014_bgc_smiles_svg"),
    ]

    operations = [
        migrations.AddField(
            model_name="protein",
            name="mgyp",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
