# Generated by Django 5.0.4 on 2025-09-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0015_protein_mgyp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="cluster_representative",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
