# Generated by Django 5.0.4 on 2026-03-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgnify_bgcs', '0018_remove_cds_uniq_cds_location_caller_pipeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='genome_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='genome_size_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='is_type_strain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assembly',
            name='isolation_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='organism_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='taxonomy_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='taxonomy_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='taxonomy_genus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='taxonomy_kingdom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='taxonomy_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='taxonomy_phylum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='taxonomy_species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='type_strain_catalog_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['taxonomy_family'], name='idx_assembly_tax_family'),
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['taxonomy_genus'], name='idx_assembly_tax_genus'),
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['is_type_strain'], name='idx_assembly_type_strain'),
        ),
    ]
