apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bgc-local
data:
  DJANGO_DEBUG: "True"
  ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0,*"
  LOG_LEVEL: "DEBUG"
  # Matomo disabled locally
  MATOMO_URL: ""
  MATOMO_SITE_ID: ""
  NUMBA_CACHE_DIR: /tmp/numba_cache
