# Generated by Django 3.2.25 on 2024-08-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('assembly_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=255)),
                ('bgcdb_accession', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'assembly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bgc',
            fields=[
                ('bgc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bgc_accession', models.CharField(max_length=255)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('bgc_metadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bgc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BgcClass',
            fields=[
                ('bgc_class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bgc_class_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bgc_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BgcDetector',
            fields=[
                ('bgc_detector_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bgc_detector_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bgc_detector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('biome_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lineage', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'biome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contig',
            fields=[
                ('mgyc', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('contig_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('contig_length', models.IntegerField(blank=True, null=True)),
                ('true_mgyc', models.BooleanField(blank=True, null=True)),
                ('sequence', models.TextField()),
            ],
            options={
                'db_table': 'contig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileMd5',
            fields=[
                ('file_md5_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_md5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'file_md5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('mgyp', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sequence', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster_representative', models.CharField(blank=True, max_length=255, null=True)),
                ('pfam', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'protein',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.IntegerField(primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'study',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('mgyp', models.OneToOneField(db_column='mgyp', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.protein')),
                ('start_position', models.IntegerField(blank=True, null=True)),
                ('end_position', models.IntegerField(blank=True, null=True)),
                ('strand', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metadata',
                'managed': False,
            },
        ),
    ]
